apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: aarishcloud-com-tls
spec:
  secretName: aarishcloud-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: aarishcloud.com
  dnsNames:
    - aarishcloud.com
    - www.aarishcloud.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - aarishcloud.com
          - www.aarishcloud.com